[debug] [2024-03-21T06:38:21.733Z] ----------------------------------------------------------------------
[debug] [2024-03-21T06:38:21.734Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\rizza\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2024-03-21T06:38:21.735Z] CLI Version:   13.5.1
[debug] [2024-03-21T06:38:21.735Z] Platform:      win32
[debug] [2024-03-21T06:38:21.735Z] Node Version:  v18.18.2
[debug] [2024-03-21T06:38:21.739Z] Time:          Thu Mar 21 2024 14:38:21 GMT+0800 (Philippine Standard Time)
[debug] [2024-03-21T06:38:21.739Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-03-21T06:38:21.742Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-03-21T06:38:21.840Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-03-21T06:38:21.840Z] > authorizing via signed-in user (rizzabhb24024@gmail.com)
[debug] [2024-03-21T06:38:21.840Z] [iam] checking project audit-tracker-d4e91 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-03-21T06:38:21.841Z] > refreshing access token with scopes: []
[debug] [2024-03-21T06:38:21.842Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-03-21T06:38:21.842Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-03-21T06:38:22.182Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2024-03-21T06:38:22.182Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-03-21T06:38:22.188Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/audit-tracker-d4e91:testIamPermissions [none]
[debug] [2024-03-21T06:38:22.188Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/audit-tracker-d4e91:testIamPermissions x-goog-quota-user=projects/audit-tracker-d4e91
[debug] [2024-03-21T06:38:22.188Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/audit-tracker-d4e91:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2024-03-21T06:38:22.292Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2024-03-21T06:38:22.292Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2024-03-21T06:38:23.378Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/audit-tracker-d4e91:testIamPermissions 200
[debug] [2024-03-21T06:38:23.378Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/audit-tracker-d4e91:testIamPermissions {}
[debug] [2024-03-21T06:38:23.378Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project audit-tracker-d4e91:

  firebase.projects.get
  firebasehosting.sites.update
[debug] [2024-03-21T06:38:23.379Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/audit-tracker-d4e91 [none]
[debug] [2024-03-21T06:38:23.954Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/audit-tracker-d4e91 403
[debug] [2024-03-21T06:38:23.954Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/audit-tracker-d4e91 {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2024-03-21T06:38:23.955Z] HTTP Error: 403, The caller does not have permission
[error] 
[error] Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier
